config/routes.rb
Soundcrowd::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  put "versions/vote_up", :to => "versions#vote_up"
  put "versions/vote_down", :to => "versions#vote_down"
  resources :scplayer
  resources :signed_urls, only: :index
  resources :production_followers, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  match '/signup', :to => 'users#new'
  root :to => "home#index"
  resources :version_votes
  match "/productions/:production_id/:controller/:id/:action"
  resources :productions do
    resources :versions
  end
  resources :versions
  scope "api" do
    resources :productions do
      resources :versions
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :token_authenticatable, :confirmable,
	# :lockable, :timeoutable and :omniauthable
	acts_as_voter
	has_karma(:versions, :as => :submitter, :weight => 7)
	devise :database_authenticatable, :registerable,
				 :recoverable, :rememberable, :trackable, :omniauthable
	attr_accessible :email, :password, :password_confirmation, 
									:remember_me, :username, :provider, :uid, :token, :avatar_url
	has_many :user_productions
	has_many :productions, :through => :user_productions
	has_many :versions, :through => :productions
 	has_many :relationships, foreign_key: "follower_id", dependent: :destroy
 	has_many :followed_users, through: :relationships,
 														source:  :followed
 	has_many :reverse_relationships, foreign_key: "followed_id",
 																		class_name: "Relationship",
 																		dependent: :destroy
 	has_many :followers, through: :reverse_relationships, source: :follower
 	has_many :production_follows, :class_name => "ProductionFollower"

 	def self.find_for_soundcloud_oauth(auth, signed_in_resource=nil)
 		user = User.where(:provider => auth.provider, :uid => auth.uid.to_s).first
 		unless user
 			user = User.create!(
 				provider: auth.provider,
 				email: "#{auth.uid}@soundcloud.com",
 				uid: auth.uid,
 				username: auth.extra.raw_info.username,
 				password: auth.credentials.token,
 				avatar_url: auth.extra.raw_info.avatar_url,
 				token: auth.credentials.token
 				)
 		end
 		user
 	end

 	def following?(other_user)
 		relationships.find_by_followed_id(other_user.id)
 	end

 	def follow!(other_user)
 		relationships.create!(followed_id: other_user.id)	
 	end

 	def unfollow! (other_user)
 		relationships.find_by_followed_id(other_user.id).destroy
 	end

 	def following_production?(production)
 		production_follows.find_by_production_id(production.id)
 	end

 	def follow_production!(production)
 		production_follows.create!(production_id: production.id)	
 	end

 	def unfollow_production! (production)
 		production_follows.find_by_production_id(production.id).destroy
 	end
 	
end
# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  username               :string(255)
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(255)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer         default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def soundcloud
		 @user = User.find_for_soundcloud_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Soundcloud") if is_navigational_format?
    else
      session["devise.soundcloud_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end


  def show
    @user = User.find(params[:id])
  end

  def following
		@user = User.find(params[:id])
		@users = @user.followed_users.paginate(page: params[:page])
		render 'show_follow'
	end
	def followers
		@title = "Followers"
		@user = User.find(params[:id])
		@users = @user.followers.paginate(page: params[:page])
		render 'show_follow'
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.haml
= form_for(current_user.relationships.build(followed_id: user.id), :html => { class: "follow" }, remote: true) do |f|
	= f.hidden_field :followed_id
	%button{:type => "submit", class: "btn-action lighten"}
		= image_tag('icons/18px/smiley.png',:class => "icon follow")
		= "follow"

app/views/users/_follow_form.html.haml
- unless current_user.id == @user.id
	.follow_form
	- if current_user.following?(@user)
		= render "unfollow", :user => @user
	- else
		= render "follow", :user => @user

app/views/users/_unfollow.html.haml
= form_for(current_user.relationships.find_by_followed_id(@user),html: {method: :delete, class: "follow"}, remote: true) do |f|
	= button_tag(:type => "submit", class: "btn-action active lighten") do
		= image_tag('icons/18px/smiley.png',:class => "icon follow")
		= "unfollow"

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
	<a href="<%= user_path(user) %>">
		<div class="user-badge" style="background-image: url('<%= 
		if FileTest.exist?("#{Rails.root}/app/assets/images/avatars/#{user.id}.png")
			then image_path("avatars/#{user.id}.png")
			else image_path("avatars/_default.png")
				end %>')">
			<span class="username"><%= user.username %></span>
		</div>
	</a>
<% end  %>

app/views/users/new.html.haml
%h1
	Sign Up
%fieldset
	%legend
		Fill out the form below
	%form{:action => "#"}
		%br
		%label{:for => "username"} Username
		%input{:type => "text", :name => "username"}
		.clr
		%br
		%label{:for => "email"} Email
		%input{:type => "text", :name => "email"}
		.clr
		%br
		%label{:for => "program"} What program do you use?
		%select{:type => "list", :name => "program"}
			%option{:value => 5} I don't have one
			%option{:value => 1} Ableton Live
			%option{:value => 2} Logic
			%option{:value => 3} Cubase
			%option{:value => 4} Pro Tools
		.clr
		%br
		%button.submit{:type=> "submit"} Submit

app/views/users/show.html.haml
- content_for :head do
	= stylesheet_link_tag "users"
= avatar(@user)
%h1.username= @user.username
%span.followers= link_to raw("<span id='followers'>")+"#{@user.followers.count}"+raw('</span>')+" Followers", followers_user_path(@user)
%span.followers#following= link_to "#{@user.followed_users.count} Following", following_user_path(@user)
= render "shared/follow_form", :user => @user