config/routes.rb
Soundcrowd::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  put "versions/vote_up", :to => "versions#vote_up"
  put "versions/vote_down", :to => "versions#vote_down"
  resources :scplayer
  resources :signed_urls, only: :index
  resources :production_followers, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  match '/signup', :to => 'users#new'
  root :to => "home#index"
  resources :version_votes
  match "/productions/:production_id/:controller/:id/:action"
  resources :productions do
    resources :versions
  end
  resources :versions
  scope "api" do
    resources :productions do
      resources :versions
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
- content_for :head do
	= stylesheet_link_tag "home"
	%meta{:content => "cU0cPkvZDWtCw8Hvn9_uRh9CmcxQWm7NKC1JsJK5Fz0", :name => "google-site-verification"}
.wrapper
	%h1.home-title{:style => "margin-bottom:20px;"}
		Create Great Music, 
		%span{:style => "color:#E45B00;"} Together.
	.homeleft
		= image_tag('hero.png',:class => "hero")
	.homeright
		%h3 Download your favorite artists' music, in raw production format
		%p SoundCrowd is a place for producing music as a crowd - By requiring the production file for all uploaded music, we hope to promote collaboration between artists. You can 'fork' songs within a production, so a production may consist of many different versions - and by allowing anyone to vote for a version, we hope to give listeners a voice in a production's direction.
		%p Sign up - it's free. All you need is a SoundClound account.
		= link_to image_tag('btn-connect-sc-l.png'), user_omniauth_authorize_path(:soundcloud), :class => "auth"
		%br
		= link_to "Check out some Projects", productions_path
		%br
		= link_to "See Users", users_path